import type { ResolvedLanguage } from "@/i18n";

const copies = {
	en: {
		title: "Automatic profiles",
		description:
			"Turn every immediate folder inside one root into an independently managed backup profile.",
		newRule: "New automation",
		emptyTitle: "No automatic profile rules",
		emptyDescription:
			"Choose a root such as Desktop or Projects. NextHive will keep one profile for direct files and create a separate profile for every child folder.",
		name: "Automation name",
		nameHint: "Used for files directly inside the root folder.",
		root: "Root folder",
		browse: "Browse",
		identity: "Folder structure",
		identityDescription:
			"Immediate folders are recursive profiles. Files directly in the root never leak into those folder profiles.",
		destination: "Git destination",
		account: "Token account",
		noAccount: "No token account",
		branch: "Branch",
		autoRepositories: "Create private repositories automatically",
		autoRepositoriesDescription:
			"Each generated profile gets its own nexthive-<profile> repository and an initial backup.",
		schedule: "Backup behavior",
		daily: "Daily backup",
		dailyTime: "Daily backup time",
		onStartup: "Back up on application startup",
		continuous: "Back up when files change",
		debounce: "Change stacking window (seconds)",
		notifications: "Backup notifications",
		filters: "Filtering & commit messages",
		excludeProfile: "Exclude profile",
		noExclude: "No exclude profile",
		aiAccount: "AI connection",
		noAi: "No AI connection",
		aiMajor: "AI messages for daily/manual backups",
		aiFast: "AI messages for change backups",
		enabled: "Automation enabled",
		create: "Create automation",
		save: "Save changes",
		cancel: "Cancel",
		creating: "Creating profiles and repositories...",
		saving: "Saving and reconciling...",
		edit: "Edit",
		sync: "Check now",
		pause: "Pause",
		paused: "Paused",
		resume: "Resume",
		remove: "Delete",
		active: "Active",
		missing: "Missing",
		error: "Needs attention",
		directFiles: "Direct files",
		folderProfile: "Folder profile",
		profiles: "generated profiles",
		lastChecked: "Last checked",
		never: "Not checked yet",
		detachConfirm:
			"Delete this automation and retire {count} generated backup profile(s)? Original files and remote repositories will not be touched.",
		keptNotice:
			"Deleting an automation removes its generated profiles from NextHive. Original files and remote repositories are kept.",
	},
	tr: {
		title: "Otomatik profiller",
		description:
			"Tek bir kök dizindeki her doğrudan klasörü bağımsız yönetilen bir yedek profiline dönüştürün.",
		newRule: "Yeni otomasyon",
		emptyTitle: "Otomatik profil kuralı yok",
		emptyDescription:
			"Desktop veya Projects gibi bir kök seçin. NextHive doğrudan dosyalar için bir profil tutar, her alt klasör için ayrı profil oluşturur.",
		name: "Otomasyon adı",
		nameHint: "Kök dizindeki doğrudan dosyaların profil adı olarak kullanılır.",
		root: "Kök dizin",
		browse: "Seç",
		identity: "Klasör yapısı",
		identityDescription:
			"İlk seviyedeki klasörler recursive profildir. Kök dosyaları bu klasör profillerine karışmaz.",
		destination: "Git hedefi",
		account: "Token hesabı",
		noAccount: "Token hesabı yok",
		branch: "Branch",
		autoRepositories: "Private repository'leri otomatik oluştur",
		autoRepositoriesDescription:
			"Her üretilen profil kendi nexthive-<profil> repository'sini ve ilk yedeğini alır.",
		schedule: "Yedekleme davranışı",
		daily: "Günlük yedek",
		dailyTime: "Günlük yedek saati",
		onStartup: "Uygulama açılışında yedekle",
		continuous: "Dosyalar değişince yedekle",
		debounce: "Değişiklik toplama süresi (saniye)",
		notifications: "Yedek bildirimleri",
		filters: "Filtreleme ve commit mesajları",
		excludeProfile: "Hariç tutma profili",
		noExclude: "Hariç tutma profili yok",
		aiAccount: "AI bağlantısı",
		noAi: "AI bağlantısı yok",
		aiMajor: "Günlük/manuel yedeklerde AI mesajı",
		aiFast: "Değişiklik yedeklerinde AI mesajı",
		enabled: "Otomasyon etkin",
		create: "Otomasyonu oluştur",
		save: "Değişiklikleri kaydet",
		cancel: "İptal",
		creating: "Profiller ve repository'ler oluşturuluyor...",
		saving: "Kaydediliyor ve eşitleniyor...",
		edit: "Düzenle",
		sync: "Şimdi kontrol et",
		pause: "Duraklat",
		paused: "Duraklatıldı",
		resume: "Devam ettir",
		remove: "Sil",
		active: "Etkin",
		missing: "Kayıp",
		error: "İlgilenilmeli",
		directFiles: "Doğrudan dosyalar",
		folderProfile: "Klasör profili",
		profiles: "üretilen profil",
		lastChecked: "Son kontrol",
		never: "Henüz kontrol edilmedi",
		detachConfirm:
			"Bu otomasyon ve ürettiği {count} yedek profili silinsin mi? Orijinal dosyalar ve uzak repository'ler etkilenmeyecek.",
		keptNotice:
			"Otomasyon silindiğinde ürettiği profiller NextHive'dan kaldırılır. Orijinal dosyalar ve uzak repository'ler korunur.",
	},
} as const;

export function automaticProfilesCopy(language: ResolvedLanguage) {
	return copies[language as keyof typeof copies] ?? copies.en;
}
